language: python

python:
  - "2.7"
  - "3.5"

addons:
  apt:
    packages:
    - libspatialindex-dev
    - scala

before_install:
    - wget http://d3kbcqa49mib13.cloudfront.net/spark-2.0.0-bin-hadoop2.7.tgz
    - tar xvzf spark-2.0.0-bin-hadoop2.7.tgz
env:
    - SPARK_HOME=$HOME/spark-2.0.0-bin-hadoop2.7uild:$PYTHONPATH

install:
    - pip install -r requirements.txt
    - python setup.py install
    
script: nosetests -s
