language: python
python:
  - "2.7"
  - "3.5"
  - "nightly" # currently points to 3.6-dev# command to install dependencies
addons:
  apt:
    packages:
    - libspatialindex-dev
    - scala
install: "pip install -r requirements.txt"
# command to run tests
script: nosetests
