language: python

python:
  - "2.7"
  - "3.5"

virtualenv:
  system_site_packages: true

addons:
  apt:
    packages:
    - libspatialindex-dev
    - scala
    - python-numpy

before_install:
    - wget http://d3kbcqa49mib13.cloudfront.net/spark-2.0.1-bin-hadoop2.7.tgz
    - tar xvzf spark-2.0.1-bin-hadoop2.7.tgz
env:
    - SPARK_HOME=$HOME/spark-2.0.1-bin-hadoop2.7 PYTHONPATH=$SPARK_HOME/python/lib/py4j-0.10.3-src.zip:$PYTHONPATH

install:
    - pip install -r requirements.txt
    - python setup.py install
    
script: nosetests -s
